### ISSUE TITLE
todo...

### ISSUE THREAD

**Issue by yaewon0411** [Develokit/K-HACKATHON-BackEnd#68]
- [x] 노인 삭제 api 추가
- [x] 보고서 분석 로직 구현
- [x] 주간 보고서 정량적 평가 페이지 조회 api
- [x] 주간 보고서 정성적 평가 페이지 조회 api
- [x] 월간 보고서 정량적 평가 페이지 조회 api
- [x] 월간 보고서 정성적 평가 페이지 조회 api
